name = "miguelzin-du-corte"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "miguelzin-barber-db"
database_id = "61d8534b-db05-495d-b91a-651ec67b7763"
migrations_dir = "prisma/migrations"

[vars]
NODE_VERSION = "20"

# JWT_SECRET precisa estar nas env vars do Cloudflare Pages, não aqui
# DATABASE_URL é só pra dev local (file:./dev.db)